### ISSUE TITLE
List All Users

### ISSUE THREAD

**Issue by AbdulSuboor-Syed** [AbdulSuboor-Syed/HandIn-HandOut#1]
We intend to create a page which will list all the registered users .

**Comment by AbdulSuboor-Syed** [comment]
Back End Requirement:

- [ ] Admin should be able to list all users from the database

**Comment by AbdulSuboor-Syed** [comment]
Front End Requirement:

- [ ] All users should be displayed in Bootstrap cards.
- [ ] There should be a button "Edit" which should redirect the admin to a page where they can edit user information
- [ ] There should be a button  "Delete" which should allow the admin to delete a user from the database.

**Comment by AbdulSuboor-Syed** [comment]
Complete List All Users

**Comment by AbdulSuboor-Syed** [comment]
Testing Criteria:

- [ ] Admin is able to list all users
- [ ] Admin is redirected to a link on clicking on edit button
- [ ] Admin is redirected to a link on clicking on delete button

**Comment by HimajaParachuri** [comment]
All the list users is working. 
Edit and Delete button is redirecting from the link.
