### ISSUE TITLE
Edit User

### ISSUE THREAD

**Issue by AbdulSuboor-Syed** [AbdulSuboor-Syed/HandIn-HandOut#2]
The admin should be able to edit user information if need.

**Comment by AbdulSuboor-Syed** [comment]
- [ ] Admin is able to edit user information
- [ ] User is redirected to edit user page from list users page

**Comment by HemaSreeRathnamMachha** [comment]
All criteria have been met

**Comment by AbdulSuboor-Syed** [comment]
- [ ] In edit user page information is editable 
- [ ] Button for manage roles
- [ ] Button for manage claims

**Comment by tata1141** [comment]
all criteria have been met

**Comment by AbdulSuboor-Syed** [comment]
Testing:

- [ ] Admin is able to edit any user information
- [ ] Admin is able to edit user information

**Comment by HimajaParachuri** [comment]
Test cases working successfully.
