### ISSUE TITLE
Set Up Delete Confirmation

### ISSUE THREAD

**Issue by AbdulSuboor-Syed** [AbdulSuboor-Syed/HandIn-HandOut#4]
There should be confirm delete option once the admin clicks on delete button

**Comment by AbdulSuboor-Syed** [comment]
- [ ] Once a admin clicks on delete it shows a span which says confirm delete.
- [ ] Admin is able to delete a user

**Comment by HimajaParachuri** [comment]
Admin can delete a user successfully.
