### ISSUE TITLE
Manage User Claims

### ISSUE THREAD

**Issue by AbdulSuboor-Syed** [AbdulSuboor-Syed/HandIn-HandOut#6]
We intend to create policies to allow certain users the ability to assist admin in maintaining the website . To give privilege's to users the admin should be able to do it while clicking on manage user claims> clicking on check boxes to allow editing the data , creating the data and deleting the data

**Comment by HimajaParachuri** [comment]
Admin able to manage the user claims.
Check boxes working after testing to edit the data, create the data and delete the data.
