### ISSUE TITLE
Creating Collaborators role

### ISSUE THREAD

**Issue by AbdulSuboor-Syed** [AbdulSuboor-Syed/HandIn-HandOut#9]
We intend to create a role of collaborator which is has access to the catalog of books. Based on admin requirements they can edit, delete or create books. and also have access to the pages restricted to normal users

**Comment by HimajaParachuri** [comment]
Testing for the collaborators role where admin can edit, delete and create books and also admin can restrict some of the users.
All the test cases are working.
